### PR TITLE
New tree reader

### PR DESCRIPTION
**Pull request by lwming**
pushing Sean's treeReader stuff into github, small update to YggdrasilEventVars.h to make code compile. Please check if there are any non-foreseen problems. Thanks

### CODE REVIEW

**Comment by hsatoshi** [comment]
[1] The variable to be stored to numTruePV_ is float.
Change the code which use the class...

[2] What is the point of the modification of the order of declaration of 
 passHLT_Ele27_eta2p1_WPTight_Gsf_v_ 
and
 passHLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v_ ?
Is any code sensitive to the order ?
Is this modification really needed ?

[3] Introduce of variables which is unsupported in tuple maker side.
I understand this is an easy way from technical point of view,
 but I hesitate to re-introducing obsolete variables.
[3-1] How much is it hard to remove them from the code?
[3-2] If we have to do this, it is good to resuscitate some of them (PUPPI iso, for example) at this opportunity.

**Comment by lwming** [comment]
[1] okay, I'll update the type to "float"
[2] I don't think the order matters, that's just a leftover of the code updating process
[3] I agree that we should try to avoid obsolete variables, but this extra one saves a lot of trouble downstream. Since it's just one variable(without the systematics), I think it should be fine. Adding a few other potential useful variables are also fine too if necessary.

What's the best way to proceed? Should I close this request, update the code and send a new pull-request?

**Comment by hsatoshi** [comment]
Thank you for your comments.

[1] thank you.
[2] Is it possible to make this part of the code back?
     The code should remains the same as mush as possible in order to avoid "conflict".
[3] I totally understand. 
      Then, could you add this variable to the variable list of README, mentioning that the variable is not used in YggdrasilTupleMaker(and not filled) but needed by XXXXX ?

Concerning the update, 
 you can push your new modifications to your repository as usual, then this Pull-request is automatically updated.
(This is why I recommended to make one dedicated branch when people send a pull-request.)

**Comment by lwming** [comment]
[2] ah, I see your point now. Yes, being consistent among different contributors will avoid any potential conflict. Unfortunately, git is not intelligent enough to ignore trivial updates.
[3]will do. The auto-update is a really nice feature.

**Comment by lwming** [comment]
Okay, I've updated the requested changes. Let me know if there are any other problems.

**Comment by hsatoshi** [comment]
👍 

I confirmed that
- the new variable is stored in the output tree (picture attached),
   which is int vector and expected to be empty for all the events. 
- new tuple file works with my tools downstream without any modification.

screen shot 2016-08-24 at 10 18 23 am

**Comment by hsatoshi** [comment]
We do not have any objections.
Merge.

**Pull request merged**
